# Generated by Django 2.2 on 2019-04-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='username',
            field=models.CharField(default='no-user', max_length=100),
            preserve_default=False,
        ),
    ]
